spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:h2:mem:helpdesk;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2-console

helpdesk:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 300000
    refresh-expiration: 3600000
  admin:
    email: ${ADMIN_EMAIL:}
    password: ${ADMIN_PASSWORD:}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  pepper:
    value: ${PEPPER}
  storage:
    local-root: ${user.home}/helpdesk-storage
  mail:
    whitelist: [ 01169622@pw.edu.pl ]

logging:
  level:
    com.example.helpdesk: DEBUG
